language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: TZAznFmhEoaHp3vhcJsdVkjAk7sL28gUi2RWsmWfOg6Zq4Z/jlnMA0E1JRDR6S5lkpsN1/AxDhVu5Pu4izcjignb7s/+VAL6WFNVAw1j53TWU5NU7jNJy/8DBYbO6t6fUD0UmZhbk09iBpbtMpFkfTiuE9CL5CZ2iO3F2U4nYcPTQRTn6fKNYvbrrYyai309PDLGV7BA1Yk254Xm3dycY9aaoUeURREdsgdc/BBincDXnMBS6eSYrqCk+GAE2k0LKjFfzujzA8LFYv05kJ/0HYA8tab/5R1moBNg2zKkg4E6XIxwZwH+dwgfaRk2+GLer3J+UmR1c8za0avXd6HK3YZNKzGxdYi/BnNpQYT6Em5moo7A6Urrs+v2hHGPkEbtChn6OGBKV28MtteW3bJG5JrwTKHGzMo4nZbcjaSkJEK8bTI8LzDsZm6P5tqeXb+rGBY1ILm2Y+cjqsQ5DXMoGhFup7eXiIToYZmnQL05LKn1WqLS9J0PGPxGsM/PXSjrao4Jp+8cIAL+P+vH7uOxWvRgq1AhclT3q6enfY6TIx8tXsEnogCzJTQXLSGs7KNFLQfiDobbAWO0vgPsUzy0rgRvXdbYdqA91FvOz+3hXipktrvUvfq0WQ56xlWyPdqgRppJIlD3SmVjGWzqYB7JwrAHIY1uDsdFzFNEEeWJqns=
