language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: mf9r7zS6+E8Zmr3kzcdzg9SAuab3sH+GYdH3Lq0z4Mb+SNW2uDgX6JUGXGsA1FwrGYSyb3PcAgRDBmXF5hxkBXecQr8L4gXFovAeF4g4QfuE6KmS/LfUHLjC4puLDJuBu3Y9q+1qQWRoeCFEP14HqiGHy7otTqJafUn/uGAXQqpb3ATBTrriGai3BN9m3DAH4NiMrACy5hq8v2HVSL+qxC2il9+dIWfPaNoRJc6AgOBucwCHOgj7dPtRAmzSZRrYJNQqApEzYn11eHvZIc57prvJKay2V1CzuFsLC+duIrXC1QolTzXr2Kdc2ffNelfJtBPeU54Tw926dFB+U0KvS74eu7r49YcZpLiKPbtaUVQhIXe7hrgEgPEGOZSpu+vvz1vVmUFmU5/Lm29Pb7aj8v2T4Z78y87wC6jxxm+0AlZOVf+vCdtQn/ryXcnNcqoXRDapjOSgnGY129a59/v9spugNufkXzjq3UKq9tw64rCXRU/R6j9rPa5Wvh8bWXlP2344cy3wasYk9THE8VJa/7ymGMzrakiaX0/egNmZdL46TtCT0jsVu13DvqXjU1Z+K22yXbyuIuApuiFIhyF1/VMVXXczvDudTl+VQYjEXk/tqaueaJaLK6Fx+VCooKnhCWg2+0UWMRTNpJxXngsejzch9Ztc4b/YZqS7PrWFpFQ=
  app: aqueous-forest-43046
  on:
    repo: jwang04/projet
addons:
  code_climate:
    repo_token: f4d10e48d3d634fc675698b4021c94649f2ec37cbfa009a255beaf6869f9ee48
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
