language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: oKdpwXWwrN7+rz28rCoGgidVSrRTLHcU5OkGIxR0WigZwAKBTDeCUeUsR/INwcjKytKcwyhs9PCDqovje789Imxwa5VvO7B2jLI6QVPNBQUMXiWgEhZEp1ATTaXq2SNlqPbXMfjKkNBOpqqCVjv/LJk/LdExhTf3IVbEWkTQX22XpUupUJDEKk732v7Kr1XJ5g/LVfAlNbadv3YIBfyPIeRtomCVdPWL88wjnLB++8Odtz50pEGkzojbWtRKpURPxopiYrPsLhXKVKcJdXGX2mxCCNts8LnXQbaW/aqX3dzZOddr4d9kQlSnjtVVH5RpkpZMUO9Et9Mkf03ddqSKakwF+ORJ6Mf3pDEmoBJRu80SK090fbQhN07f1DlBPlEf3AO8u6LGwU0ArEvNh+37ICCOsR6ZEL5vpe4MQ4Kmkhyf3jkG8/8BW47AsSacTpBycsZPJ6deWTg8nTTfLjYLkrFzjmUDhwM9nJb5ukdpy2h0X//NPDbCQcl1wammAC51ZzhLQDHDZhbDAdCWqM0VIe+VdDSXgtpNQ8LOPZ3xwFo1na/mPW3HZnJ9QeyTHa1M8NBaEcLVSz43dsc5HToE70fxB3rbNHY+vjVxXZWz/ACmIhtLrks37VH2dCSkl4SJHjcZYdE9vEGOj6r3bgaPYykivVjQrLX/6pNE1neN5pA=
  on:
    repo: zeyizhou/projet
