language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: CTiREVvGje8hieUljfK+T214/EzgWVb3GaQBGCS7QtnArnl2poZADGCkcGUBvxfljueIvCXH9+UXasMz5zfrgMoVFuWen6QWZgmeRHxcV3Tfh41C1zLrJNjy7pCG/4MJKjFtg6vQ5VL7Gz2ixdZiWWMUm34/wnhRGNSPFxFL2VrVmcF58BNIinIHxDtk07xBEEOd6KjM8QT0tWY6UFVUoFtX2OFq6dnWbrLMn5e0FH+/lkwslZltaDFg+suNUC6/Wtc0o8UZxf1NGl7uijq+FtHrOGF355lF91ixZrTQWIktARVbUhMeC2d3Dm9gumlGdqXU+aD+2+bl2C/O8m3EbUu3hXIFPcKjINTzg+084x2OoYbmC41c1EZT9QzJVfgpeo1C1J1zDu/biKiNX32pZ5IJRfeJ0ZHO+M7bT0UnwxQwevaA0ujn3KtNsyWPPisDqyoRllmzR/BhSZuhuFFqroaeLdNkThP8zX4HKezG2lQd7lcJ10IFG7kXdmDvDC/Yx8DbOOAX4SRQc9ZDzsSgA4tA8uXUM4wm3GIuOa12WokwtT8undqaK88I3uQFeB9ZOrdOYx8j2TqssERSg5SExrZcOHBF/i8VM9dpEq1ZuNjPZ418jGvwHg0tAoLrjUFU2nWeNZ14krllpI9KRQ38t8u5SSzFkmIw2NkLoFydwp0=
  app: shrouded-ocean-96124
  on:
    repo: zeyizhou/projet
