language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: WyZ+hoXgktTWrWQKQyyguskPZByMDV7Ye+zo1chiwnwgCdl7wS2zxzlXGb2ZDziBmu5XVzLbOKve5ml6MLmqYki3mBXBbH2wVY6NYNPlVyCjf6EuC8kokxaOEP/+oiCby5gsG0GSaL5EDjQMkofDbCAh/+i5PJNNj85Q9zOQXUab4rmIr3YC5r7geUVABQC/ZRaQYZnKU+OasFZa0yYUlPduVJCskdR6ZakO/AczOvLcbskwv/HHCr2pm8lxbU/DaW6iuOkpMfKsKb2GbmupboyriFDphipLMe1jYg1qzwl+vVy1fq3E6IJ5xX/yqpvcTISrnVvnwXjYMxFVgZphl0yg1TnN5MTuDBAxEqBLBYGrpxKnVnHEZ80JodpSx1pkAWs3KpFzMsMnqh48oQgofu+WnAMt5YfjTzihyN7DSYG+j51ObFhjW0bNCTUgEHgMy+Wp3Sb97LxAuN97B+frLsePmpx1A4xVUmekCWocEuoUOJoLVMF1P9Oh47lcUBtNDuZtfMDBIGyGScZwoDU8E8k7BkM+2MuZi/Mi8YaeE5UbOHLIC3GrUcWofDnRcNO/e48CULkVhlYB8dDHTeoqvmeEVmWMw4D/1MZOEDV8AzOULUO3tWG1fbpZ+8oKTD1zuZX9y1a3NXWh25lHapO5kGCBRPa/cEPLkjxvQGUoOVI=
  app: intense-inlet-25592
  on:
    repo: zeyizhou/projet
