language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: h7r7FJiTVH9JTu4CIucNaSjdC+BYlZ6R+aBIl8SxLfZTVVjg47DhvbMhr+H7LSQVcCQIdy+eD7JWBb4yX7Sauvfxr7Q8amIKDLRkEu5KuZjoemJDWzGg0xAqHJo8fyxnBN6l+rtv4sikthXJhFf/oHuhJIoqHc6P+Iumi5gKxNuaOJ9l0MG2e6k8/7brzUZXRtOAbZCLCv/jD97YTy1okbNEqti3mwd4u6U6PLXV03y/mmAB6kR4uIoWaEuo8pOgh+eq0ExaMIjhV/cNZpYd8qLM1TbXpCsucfWJA57HgHEfpl5JG6eFA6QeUpHw2D/Kqd+/t7U2nO3Ze72O7/auf2rQE7/+bVu63m2xGMpByJr4FVL9WI/G9VxBxlRfq9BJYsKZM91maiqf96KM1ZDjd/ECV+2GCwgk/dz5sGQUOadqYVNkm/UUabhOLJhNSRYC6qgdjvWriaDSZfFQfKG3QEoS0d8zFDS53d8YFkHiCtT23IWYfidsYhf5/T8Z9VmSRcogAGfhjdTYxgjKkj3Z/DlU+xgCbd/5bsfJsQYpOND4uo6LENVJ6r+Mog5zQf770949xXcvnmAyLx2EwUXJE7FtNF1ZCrt1Rc8HM3487XhI0faCo0Gk4RAjVubOeKD7DrdgEc92Hn8pYsF/qDnuA3gu8NDsnQlruzk6S7no8Cs=
  app: aqueous-forest-43046
  on:
    repo: jwang04/projet
addons:
  code_climate:
    repo_token: f4d10e48d3d634fc675698b4021c94649f2ec37cbfa009a255beaf6869f9ee48
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
